package ga.spring.hiber.model;
// Generated 06/07/2017 07:53:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idventa;
     private Producto producto;
     private Usuario usuario;
     private Date fecha;
     private int tipoComp;
     private String lugar;
     private Detalle detalle;

    public Venta() {
    }

	
    public Venta(Producto producto, Usuario usuario, Date fecha, int tipoComp) {
        this.producto = producto;
        this.usuario = usuario;
        this.fecha = fecha;
        this.tipoComp = tipoComp;
    }
    public Venta(Producto producto, Usuario usuario, Date fecha, int tipoComp, String lugar, Detalle detalle) {
       this.producto = producto;
       this.usuario = usuario;
       this.fecha = fecha;
       this.tipoComp = tipoComp;
       this.lugar = lugar;
       this.detalle = detalle;
    }
   
    public int getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getTipoComp() {
        return this.tipoComp;
    }
    
    public void setTipoComp(int tipoComp) {
        this.tipoComp = tipoComp;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Detalle getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(Detalle detalle) {
        this.detalle = detalle;
    }




}


